### ISSUE TITLE
To-do list: Database

### ISSUE THREAD

**Issue by lewmilburn** [lewmilburn/hotel-app#1]
### Users
- [x] Create
- [x] Retrieve
- [x] Update
- [x] Delete
### Rooms
- [x] Create
- [x] Retrieve
- [x] Update
- [x] Delete
### Bookings
- [x] Create
- [x] Retrieve
- [x] Update
- [x] Delete

**Comment by lewmilburn** [comment]
### Coursework requirements

- [ ] Uses a database (either MongoDB or PouchDB) to store information and pass it to the client through an API.
- [ ] WebSockets should be used to enable communication between two clients.
- [ ] You must produce a working system, comprising a client constructed using dynamic web technologies (HTML, CSS and JavaScript) and a server using Node.js (no other server is permitted).
- [ ] The application must use JavaScript as the main development language both client-side and server-side (no other language is acceptable).
- [ ] The system must be interactive, i.e., the user should be able to affect its behaviour by interacting with it using a suitable input device (such as keyboard and mouse).
- [ ] The system must run on multiple computers, i.e., it must be distributed.
- [ ] Include CRUD functionality for at least 3 entities.
- [ ] Include appropriate security considerations (such as a login system)
- [ ] Be selected from one of the following topics and include appropriate functionality
